### ISSUE TITLE
Distribution idea

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.py#1]
It should be effortlessly simple to install,

No dependencies, it should be one single binary with static linking to zlib, libuv, OpenSSL. It should use python limited API, making one binary compatible across multiple python releases.

The integration with uvloop is optional but needed to get anything real working. It will rely on the relatively stable ABI of libuv for that.

One single binary for Linux, prebuilt by github actions. No compiler needed.

If pip is liberal, use it

**Comment by alexhultman** [comment]
* pip is liberal, I love it
* no need to worry about ABIs other than Python

Problem solved, will kick ass

**Comment by dalisoft** [comment]
@alexhultman Hi 😀
I new to Python, i come to Python for trying AI things + interesting to uWebSockets.py.

At first install, i got error

### variant 1

```bash
❯ pip install uWebSockets.py
ERROR: Could not find a version that satisfies the requirement uWebSockets.py (from versions: none)
ERROR: No matching distribution found for uWebSockets.py
```

### variant 2

```bash
❯ pip3 install uwebsocketspy
ERROR: Could not find a version that satisfies the requirement uwebsocketspy (from versions: none)
ERROR: No matching distribution found for uwebsocketspy
```

Other libraries such as `tensorflow` installing ok, is there anything wrong doing me or any way to install?

Thanks

**Comment by alexhultman** [comment]
I haven't uploaded anything yet
