### ISSUE TITLE
The python world doesn't work like this

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.py#12]
I've been made aware Python developers don't really work like this.

There's WSGI and now ASGI and uvicorn is the front runner in performance here. Then they put some "framework" on top like Django, etc.

To gain any kind of traction in the Python world there must be two things: seamless asyncio support (done), and ASGI support.

Also, the naming "uWebsockets.py" doesn't make sense in Python world, that's not how people name things. And there is not really any kind of "brand" value in uwebsockets for python - nobody knows what uwebsockets is there. It's really only a thing in JS world.

So I would say, change name entirely, go for ASGI compatibility, then expose pub/sub (which is important) as non-standard extensions under ASGI (that looks possible, and they might get standardized at some point anyways).

Then, if people care enough to use it, maybe look at transitioning to our own interfaces. But to gain immediate traction this project must be entirely compatible with ASGI.

The postfix "corn" is used in Python, so a name ending with corn would be nice to have.

**Comment by globophobe** [comment]
Closest library to this for python seems to be       https://github.com/aaugustin/websockets That library obviously has a name advantage.

One thing that’s nice, is to have both client and server implementation.

**Comment by alexhultman** [comment]
Problem with these Python "frameworks" is that they all perform like a 200 year old man with testicles hanging down to his feet.

This supposedly "uvicorn" that's "fastest" runs like a complete joke. Then you have these "framworks" atop cut down performance by 100%, from an already horrible starting point. You end up with 1/1000 the expected performance.

It's a fundamental rape on the English language to describe these projects as "fast" and complete lunacy with "fastest".

**Comment by alexhultman** [comment]
Alright, fuck the Python way. ASGI will never scale and all these "frameworks" are pure cancer.

I can finish this project up like originally intended, then add it to some shitty benchmark and score a million times any previous Python project. Then people can do whatever they want, I don't care.
