### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.py#4]
For those of you who installed from pip on Linux, did it run? Did the examples work? What's your feedback this early in?

**Comment by Tlewis334** [comment]
![AllBoostersGo](https://user-images.githubusercontent.com/15329210/73027461-5b082e00-3e2b-11ea-824f-e3aaeb141e31.png)

The examples seem to be working for me on Linux , I know you didnt ask about windows but I checked on there as well and windows throws an import error. Great work though!

**Comment by alexhultman** [comment]
Great! I just barely got it sticking together today so that's really great

**Comment by dalisoft** [comment]
@alexhultman Is there possible add some way of modify instances of `req`, `req` at C++ level?
I tried optimize, but fails (JS/Python both).
Like this.

```python3
import HttpRequest from uws

class HttpRequest2(HttpRequest):
  def __init__(self):
    self.path = self.getUrl()

HttpRequest.extend(HttpRequest)
```

Then we don't need modify `req`, `res` on every request and performance will be better on complex servers.

**Comment by alexhultman** [comment]
I have no idea what you mean. This repo has nothing to do with JavaScript and there is no voting process, esp not on your own comments

**Comment by alexhultman** [comment]
I've tested on both macOS and various Linuxes and it seems to work really well now. On Fedora you even have python3 installed by default so you can get started in 5 seconds on a liveCD, that's pretty cool
